---
title: "Frequently used R codes"
author: "Debajit Ghosh"
date: "July 7, 2015"
output: html_document
---
## This markdown file contains frequently used R codes 
## Download a file from the web, XML, JSON

### download.file("Url",destfile="", method="curl")

### library(XML)
### xmlfile <- xmlTreeParse("Url",useInternal=TRUE)
### rootNode <- xmlRoot(xmlfile)
### xmlName(rootNode)
### rootNode[[1]]
### rootNode[[1]][[1]]
### xmlSApply(rootNode,xmlValue)
### xpathSApply(rootNode,"//li=[@class='']",xmlValue)

### library(jsonLite)
### fromJSON("Url")
## Writing data frames to JSON
### toJSON(filename,pretty=TRUE)
## Convert back to JSON
### fromJSON(filename)

## Reading data in flat files or excel sheets
### read.table("",sep="",header=TRUE,quote="",na.strings="NA",nrows=,skip=)
### library(xlsx)
### read.xlsx("",sheetIndex=,header=TRUE,colIndex=,rowIndex=)
## Using data.table to do single function statistical summary operations, add new columns, merge and subset 
### datatable[,list(mean(x),sum(z))]
### datatable[,table(y)]
### datatable[,newcol:=expression]
### datatable[,newcol:={name <- operation1; operation2}]
### datatable[,a:=x >0]
### datatable[,b:=mean(x+w),by=a]
## Merge datasets using the same set key
### 1. setKey(datatable1,colName) 
### 2. setKey(datatable2, colName) 
### 3. merge(,)
### datatable['colname']
## Fast reading
### 1.file <- tempfile()
### 2. write.table(dataset, file=file, row.names=FALSE, col.names=TRUE, sep="",quote=FALSE)
### 3. system.time(fread(file))

## Constructing R graphics
### 1.boxplot(data$col, col="blue")
### 2.abline(h=12)
### 1.par(mfrow=c(2,1), mar=c(4,4,2,1)) 
### 2.hist(subset(data,data$col=="")$column, col="blue")
### 1.hist(data$col,col="blue",breaks=100)
### 2.rug(data$col)
### 3.abline(v=12,col="",lwd=,lty=)
### 1.barplot(y~x,data=datasetname,col="wheat",main="title")
### 1.with(dataset, plot(x,y,col="blue"))
### 2.abline(h=,lwd=,lty=)

## Lattice Plotting System
### xyplot(y~x|f*g,data)
## eample 
### airquality <- transform(airquality, Month=factor(Month))
    xyplot(Ozone~Wind | Month, data=airquality, layout=c(5,1))
### panel function in lattice
## example
xyplot(y~x | f, panel=function(x,y,..){
panel.xyplot(x,y,...)
panel.abline(h=median(y),lty=2)
})
## ggplot2 - quick plot 
### qplot(displ,hwy,data=mpg,color=drv)
### qplot(displ,hwy,data=mpg,geom=c("point","smooth"))
### qplot(hwy,data=mpg,fill=drv)
### qplot(log(eno),data=maacs,geom="density")
### qplot(log(pm25),log(eno),data=maacs,shape=mopos, color=mopos)
### qplot(log(pm25),log(eno),data=maacs,color=mops,geom=c("point","smooth"),method="lm")
## ggplot
### g <- ggplot(df,aes(,))
### g+geom_point(color="steelblue",size=4,alpha=1/2)+geom_smooth(method="lm")
### g+geom_point(aes(color=bmicat),size=4,alpha=1/2)
### g+geom_point()+facet_grid(.~bmicat)+geom_smooth(method="lm")
### g+geom_point(aes(color=bmicat))+labs(title="")+labs(x="",y="")+geom_smooth(size=4,linetype=3,method="lm",se=FALSE)
### g+geom_point(aes(color=bmicat))+theme_bw(base_family="Times")
### g+geom_line()+coord_cartesian(ylim-c(,))

### caalculate the deciles of the data
cutpoints <- quantile()
### Cut the data at deciles
cut(,cutpoints)
### see the levels
levels()



## facets
qplot(displ,hwy,data=mpg,facets=.~drv)
qplot(hwy,data=mpg,factes=drv~.,bindwidth=2)
## Using dplyr package
## 1. Creating a dataframe : x.df <- tbl_df(data)
## 2. Multiple data manipulation operations using dplyr:
result3 <-
  cran %>%
  group_by(package) %>%
  summarize(count = n(),
            unique = n_distinct(ip_id),
            countries = n_distinct(country),
            avg_bytes = mean(size)
  ) %>%
  filter(countries > 60) %>%
  arrange(desc(countries), avg_bytes)
print(result3)

## MySQL
ucscDb <- dbConnect(MySQL(), user="genome",
                             host = "genome-mysql.cse.ucsc.edu")
result <- dbGetQuery(ucscDb,"show databases;");dbDisconnect(ucscDb);

hg19 <- dbConnect(MySQL(),user="genome",db="hg19",host="genome-mysql.cse.ucsc.edu")
allTables <- dbListTables(hg19)
dbListFields(hg19,"affyU133Plus2")
dbGetQuery(hg19,"select count(*) from affyU133Plus2")
affyData <- dbReadTable(hg19,"affyU133Plus2")
query <- dbSendQuery(hg19,"select * from affyU133Plus2 where misMatches between 1 and 3")
affyMis <- fetch(query);quantile(affyMis$misMacthes)
affyMissSmall <- fetch(query,n=10);dbClearResult(query);
dbDisconnect(hg19)

## RHDF5 package
source("http://bioconductor.org/biocLite.R")
biocLite("rhdf5")
### create hdf5 file: 
created = h5createFile("example.h5")
### create groups with the hdf5 file
created = h5createGroup("example.h5","foo")
created = h5createGroup("example.h5","baa")
created = h5createGroup("example.h5","foo/foobaa")
## list
h5ls("example.h5")
## write to groups
A = matrix(1:10,nr=5,nc=2)
h5write(A,"example.h5","foo/A")
B=array(seq(0.1,2.0,by=0,1),dim=c(5,2,2))
attr(B,"scale") <- "liter"
h5write(B,"example.h5","foo/foobaa/B")
h5ls("example.h5")

h5write(df,"example.h5","df")
h5ls("example.h5")
## read data
readA = h5read("example.h5","foo/A")
readB = h5read("example.h5","foo/foobaa/B")
readdf = h5read("example.h5","df")
readA

h5write(c(12,13,14),"example.h5","foo/A",index=list(1:3,1))
h5read("example.h5","foo/A")

## read web data
con = url("")
htmlCode = readLines(con)
close(con)
htmlCode
## Parsing with sml
url <- ""
html <- htmlTreeParse(url, useInternalNodes=T)
xpathSApply(html,"//title", xmlValue)

## get from httr packages
library(httr);html2=GET(url)
content2 = content(html2, as ="text")
parsedHtml = htmlParse(content2, asText=TRUE)
xpathSApply(parsedHtml,"//title",xmlValue)

## accessing websites with passwords
pg1 = GET("",authenticate("user","passwd"))

google=handle("")
pg1 = GET(handle=google,path="/")
pg2 = GET(handle=google,path="search")

## reading data from api (application programming interface)
my app = oauth_app("",key="",secret="")
sig = sign_oauth1.0(myapp, token="",token_secret="")
homeTL = GET("",sig)

## converting the json object
json1=content(homeTL)
json2=jsonlite::from JSON(toJSON(json1))
json2[1,1:4]

## reading from other sources
